---
services:
  mumble:
    image: mumblevoip/mumble-server:latest
    ports:
      - "64738:64738"
      - "64738:64738/udp"
    volumes:
      - mumble_data:/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    runtime: nvidia
    privileged: true
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  # NOTE: Don't use assistant service, it isn't ready.
  # assistant:
  #   build:
  #     context: .
  #     dockerfile: assistant.Dockerfile
  #   image: assistant:latest
  #   volumes:
  #     - assistant_data:/data/piper-models
  #     - assistant_data:/data/whisper-models
  #     - assistant_data:/data/vad-records
  #   restart: unless-stopped
  #   depends_on:
  #     - ollama
  #     - mumble
  #   environment:
  #     - MUMBLE_SERVER_HOST=mumble

volumes:
  mumble_data:
  ollama_data:
  assistant_data:
