---
services:
  mumble:
    image: mumblevoip/mumble-server:latest
    ports:
      - "64738:64738"
      - "64738:64738/udp"
    volumes:
      - mumble_data:/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    runtime: nvidia
    privileged: true
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  whisperx-api:
    build:
      context: https://github.com/zatevakhin/whisperx-api.git
      dockerfile: gpu.Dockerfile
    runtime: nvidia
    privileged: true
    volumes:
      - whisperx_data:/models
    ports:
      - "8000:8000"
    restart: unless-stopped


volumes:
  mumble_data:
  ollama_data:
  whisperx_data:
