import os

PIPER_MODELS_LOCATION = os.environ.get("PIPER_MODELS_LOCATION", "data/piper-models")
PIPER_TTS_MODEL = os.environ.get("PIPER_TTS_MODEL", "en_US-amy-medium")

SPEECH_PIPELINE_SAMPLERATE = 16000
SPEECH_PIPELINE_BUFFER_SIZE_MILIS = 32

ASSISTANT_NAME = os.environ.get("ASSISTANT_NAME", "Aya")

VAD_SILENCE_THRESHOLD = int(os.environ.get("VAD_SILENCE_THRESHOLD", 16))

